### ISSUE TITLE
GitHub Actions配置参考

### ISSUE THREAD

**Issue by yeshan333** [yeshan333/actions-for-hexo-blog#5]
- http://www.ruanyifeng.com/blog/2019/09/getting-started-with-github-actions.html
- https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by yeshan333** [comment]
第一次使用的 CI 不知道为什么对 git log 有破坏性变更

```yaml
# workflow name
name: Hexo Blog CI

# master branch on push, auto run
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master

    # from: https://github.com/actions/setup-node
    - name: Setup Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: "10.x"

    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g
        npm install
    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Setup Git Infomation
      run: |
        git config --global user.name 'yeshan333'
        git config --global user.email '1329441308@qq.com'
    - name: Deploy Hexo
      run: |
        hexo clean
        hexo generate
        hexo deploy
```

**Comment by yeshan333** [comment]
> 第一次使用的 CI 不知道为什么对 git log 有破坏性变更
> 
> ```yaml
> # workflow name
> name: Hexo Blog CI
> 
> # master branch on push, auto run
> on:
>   push:
>     branches:
>       - master
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
> 
>     steps:
>     # check it to your workflow can access it
>     # from: https://github.com/actions/checkout
>     - name: Checkout Repository master branch
>       uses: actions/checkout@master
> 
>     # from: https://github.com/actions/setup-node
>     - name: Setup Node.js 10.x
>       uses: actions/setup-node@master
>       with:
>         node-version: "10.x"
> 
>     - name: Setup Hexo Dependencies
>       run: |
>         npm install hexo-cli -g
>         npm install
>     - name: Setup Deploy Private Key
>       env:
>         HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
>       run: |
>         mkdir -p ~/.ssh/
>         echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
>         chmod 600 ~/.ssh/id_rsa
>         ssh-keyscan github.com >> ~/.ssh/known_hosts
>     - name: Setup Git Infomation
>       run: |
>         git config --global user.name 'yeshan333'
>         git config --global user.email '1329441308@qq.com'
>     - name: Deploy Hexo
>       run: |
>         hexo clean
>         hexo generate
>         hexo deploy
> ```

若不想把 Page Repo 的 git log 摧毁，`hexo deploy` 前添加 `git clone git@github.com:yeshan333/yeshan333.github.io.git .deploy_git`

**Comment by yeshan333** [comment]
```yaml
name: Site CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: "12.x"

      - name: Setup Dependencies
        run: |
          npm install hexo-cli -g
          npm install
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "1329441308@qq.com"
          git config --global user.name "yeshan333"
          git clone git@github.com:yeshan333/yeshan333.github.io.git .deploy_git
          hexo clean
          hexo generate
          hexo deploy
```
